version: "3.9"

services:
  nvidia-container-runtime:
    container_name: nv-con-runtime
    image: nvidia/cuda:11.0-base
    runtime: nvidia
    privileged: true

    # devices:
    #   # - /dev:/dev
    #   - /dev/nvidia0:/dev/nvidia0
    #   - /dev/nvidiactl:/dev/nvidiactl
    #   - /dev/nvidia-caps:/dev/nvidia-caps
    #   - /dev/nvidia-modeset:/dev/nvidia-modeset
    #   - /dev/nvidia-uvm:/dev/nvidia-uvm
    #   - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    entrypoint: ["nvidia-smi"]

  nvidia-container-toolkit:
    container_name: nv-con-toolkit
    image: nvidia/cuda:11.0-base
    # privileged: true

    devices:
      # - /dev:/dev
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-caps:/dev/nvidia-caps
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # equivalent for gpus = 1, if this is not set, gpus = all
              capabilities: [gpu]
    entrypoint: ["nvidia-smi"]

  object-detection:
    container_name: object-detection
    image: mingkhoi/ubuntu-18.04-tensorrt8-tf2.6:version1.0
    volumes:
      - ./data:/home/howard/object-detection/data:rw
      - ./meta:/home/howard/object-detection/meta:rw
      - ./container_share.log:/home/howard/container_share.log:rw
      - ./src:/home/howard/object-detection/src:rw
    # runtime: nvidia
    # privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    devices:
      # - /dev:/dev
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-caps:/dev/nvidia-caps
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    network_mode: "host"
    # networks:
    #   collaborative-recommender-network:
    #     ipv4_address: 128.0.1.2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: 1
              capabilities: [gpu]
    # entrypoint: ["nvidia-smi"]
    entrypoint: ["tail", "-f", "/home/howard/container_share.log"]

networks:
  object-detection-network:
    ipam:
      driver: default
      config:
        - subnet: "128.0.3.0/24"
